### ISSUE TITLE
testing notification fires on production: Received from LinkedIn user Kiran Sarvaiya

### ISSUE THREAD

**Issue by aayush-khandelwal** [Share-Impact/iOS-Impact-Issues#13]
**Describe the bug**
The user is receiving a lot of notifications daily. The date of notifications is also weird.

**To Reproduce**
NA

**Expected behavior**
NA

**Screenshots**
Added
![0 1](https://user-images.githubusercontent.com/64794993/82194245-1f323080-9914-11ea-8809-a614ec3c90dc.jpg)

**Comment by gauravchauhan677** [comment]
We have identified and fixed this issue.
