### ISSUE TITLE
Less distance JLL ISSUE 

### ISSUE THREAD

**Issue by adrija25** [Share-Impact/iOS-Impact-Issues#14]
Less distance - **JLL**

**user id- 583421 -100m
user-id- 588109 -1-3km - also getting in-vehicle alert 
user id - 582203 - 7-8km** (I have updated the workouts)

screenshot for user -582203
![IMG_6095](https://user-images.githubusercontent.com/64792558/82331754-2b94b700-9a02-11ea-9c0c-dcfe864c7dec.PNG)
![IMG_6090](https://user-images.githubusercontent.com/64792558/82331811-41a27780-9a02-11ea-9552-4183d4619c65.PNG)

**Additional context**

**Comment by nik6018** [comment]
@adrija25 
Only update the distance for Vehicle alert users.

The screenshot sent by the user is for the total distance walked by him throughout the day(from HealthKit) which obviously can't be entirely covered by Impact as we track only the distance when the app tracking is on.
Explain this to the user & don't update his distance.

**Comment by adrija25** [comment]
Yes but he is keeping the app on for 2 hours and it tracks only .25km in 2 hours..
That's less @nik6018

**Comment by nik6018** [comment]
Does he have any comparison for that 2 hours? @adrija25

**Comment by nik6018** [comment]
USAIN BOLT alert is fixed by disabling the check where we compare GPS & Pedometer distance, which can be highly inaccurate depending upon the region of indoor workout.

**Comment by nik6018** [comment]
Seems like  this issue has died down closing for now
