### ISSUE TITLE
Personalising Post with User’s 1st Name

### ISSUE THREAD

**Issue by ishannadkarni** [Share-Impact/iOS-Impact-Issues#16]
**Problem - On notification drawer, I can see ‘Nikhils post’. But on clicking it, and going to the ‘Post detail’ screen, the customisation aka personalisation is lost. I didn’t recollect whose post it was when I wanted to comment ‘congrats Nikhil>’**

**Opinion - the words ‘post detail’ is backend nomenclature, not a front end name**

**Describe the solution you'd like**
- Nikhil’s post , 
- Apoorv’s post, 
- Anuja’s post 
-- instead of ‘post detail’ as screen name.

**Describe alternatives you've considered**
- Nikhil’s streak post
- Nikhil’s post in Team Impact
- Badge post

**Additional context**
Comments and claps can get boosted if the viewer/reader knows whose post it is.

**Screenshots**
![image](https://user-images.githubusercontent.com/64792502/83347686-3d505580-a344-11ea-91f4-cfba3e068101.png)

![image](https://user-images.githubusercontent.com/64792502/83347687-417c7300-a344-11ea-9b6f-0febb7021475.png)

**Comment by AnujaPednekar** [comment]
I would also like to see profile pic of the post generator/achiever.

**Comment by ishannadkarni** [comment]
+1

**Comment by gauravchauhan677** [comment]
We have identified and fixed this issue.
