### ISSUE TITLE
Read Feed, Red 5+ dot, but no need feed

### ISSUE THREAD

**Issue by ishannadkarni** [Share-Impact/iOS-Impact-Issues#17]
**Describe the bug**
Feed was read, app was updated, in new app feed notif red dot show 5+. I clicked on it to see no new feed. No a good UEx. I expected new content and there wasn’t any.

**To Reproduce**
1. Read all feed
2. Clap on a few
3. Scroll down to read more
4. Uninstall app
5. Reinstall (latest version from TestFlight)
6. Open homepage to see Feed 5+ red dot

**Expected behavior**
There needs to be exactly the same number of feed content, or notifications as mentioned on the red notif dot number.

**Screenshots**
After clicking 5+ - first feed already has my claps 
![image](https://user-images.githubusercontent.com/64792502/83472746-997ebb00-a4a5-11ea-9d6d-2a6877d5131d.png)

 - Device: iPhoneXR
 - Version : 3.1.20 shows on app / 3.5.29(2) TestFlight

*additional information*
Fix the logic for all red notification dots and numbers once and for all, for the long term.

**Comment by nik6018** [comment]
The read count for feed is deleted once you delete the app, so after a reinstall the app has no way to determine whether the feed's were read or unread

**Comment by nik6018** [comment]
This can only be fixed if the backend stores a read count of the Feed post somewhere.
Closing this issue as of now, will pickup when we work with the backend team on this

**Comment by ishannadkarni** [comment]
Okay. If it’s an issue that occurs only when a user uninstall-reinstalls and/or after update, then it’s low priority.

**Comment by nik6018** [comment]
I think this won't be a problem even when the user updates, only when the user reinstall's
