### ISSUE TITLE
Changes made for JLL League were still visible after exiting the league

### ISSUE THREAD

**Issue by aayush-khandelwal** [Share-Impact/iOS-Impact-Issues#2]
**Describe the bug**
I exited the JLL league but I could not visit the teams section. Also, the notification center was first visible but disappeared after some time. I could see all the cause cards CTA in non impact color

**To Reproduce**
1. Exit JLL League
2. Click on Homepage
3. Check if you can see the notification icon
4. Click on teams icon
5. Clicking on it showed Error message as if I was part of JLL League
6. Check color of Cause CTA, it was non impact orange in my case

**Expected behavior**
JLL league changes should have been reversed

**Screenshots**
https://sharesmile.slack.com/archives/G0134BDA8L9/p1588225831015200

**Desktop (please complete the following information):**
 

**Smartphone (please complete the following information):**
- OS: [Android 10]
 - Version [2.14.0]

**Additional context**
Unable to reproduce it. Has happened twice in past but no sure way to reproduce the issue

**Comment by nik6018** [comment]
This is iOS section please report the issue in Android repo
