### ISSUE TITLE
No Open League Floating Action Button on IOs

### ISSUE THREAD

**Issue by ishannadkarni** [Share-Impact/iOS-Impact-Issues#23]
**No Open League Fab**

FAB on joining Open League isn’t present on ios

**To Reproduce**
1. Go to App
2. Join an open league 
3. Scroll down to Invite friends
4. No FAB

**Expected behavior**
A floating action button to nudge you to invite your friends and family to the league you just joined.

**Screenshots**
![image](https://user-images.githubusercontent.com/64792502/86198672-c6da8980-bb75-11ea-803c-2948e6207a03.png)

 - Device: [e.g. iPhoneXR
 - OS: 13
 - Version - love version on App Store

**Comment by nik6018** [comment]
Have fixed this issue and will be released sometime later this month
