### ISSUE TITLE
Get a badge in 0 miles.

### ISSUE THREAD

**Issue by ishannadkarni** [Share-Impact/iOS-Impact-Issues#24]
Get a badge in 0 miles**
On the home page, content shows 0.0miles. 

To Reproduce**
1. Go to homepage 

**Expected behavior**
Badge goal is non zero km/mi away, when 0 badge should be awarded.

Screenshot
![image](https://user-images.githubusercontent.com/64792502/86221692-dd4b0a00-bba2-11ea-97fa-cc5492a14a6b.jpeg)

 - iOS 13
- IPhone XR
- live app version as of 1 July

Additional information
It’s a home page bug

**Comment by nik6018** [comment]
Hi Ishan,
This will be in very rare scenario when you are about to achieve your badge 

Can you please post the In-progress screen ?

**Comment by ishannadkarni** [comment]
![image](https://user-images.githubusercontent.com/64792502/86233454-0f646800-bbb3-11ea-9b0c-3a8d2f9167a9.png)

Here you go (edited)

![image](https://user-images.githubusercontent.com/64792502/86233364-ee037c00-bbb2-11ea-8109-5c0d16860a21.png)

Also why is it showing me in mi. if I have km in settings?

**Comment by nik6018** [comment]
Can you please confirm if the "mi" metric is only in the badge section and rest of the app shows in "km"

**Comment by ishannadkarni** [comment]
Only in the badge content line of the homepage cause card. No where else. Now I opened the app again, and it’s in kms.

**Comment by nik6018** [comment]
Can you please check if this occurs when you switch between KM & MI distance metric ?
I haven't able to replicate it

**Comment by nik6018** [comment]
Have resolved this issue. Fix will be released sometime later in the month
