### ISSUE TITLE
Teams feature not live pop-up should get Update App CTA and content needs to be updated too

### ISSUE THREAD

**Issue by aayush-khandelwal** [Share-Impact/iOS-Impact-Issues#25]
**Describe the bug**
Clicking on any team link on older version of the app opens a pop up saying "Teams is not live yet... " which has a CTA of **OK**.
The content of this pop-up needs to be updated to something like 'Update the App' to join the team and the CTA should redirect to App store

**To Reproduce**
1. Click on Teams Join link
2. Check behavior on older iOS versions

**Expected behavior**
It should ask the user to update the app to join the team

**Screenshots**
![Screenshot_20200701-202139](https://user-images.githubusercontent.com/64794993/86344997-9a5b6600-bc78-11ea-9ea1-2a0ddecc7973.jpg)

**Desktop (please complete the following information):**
Not available since sent by a user and he updated it before checking the app version

**Smartphone (please complete the following information):**
Not available

**Additional context**
NA

**Comment by nik6018** [comment]
The PopUp fetches it content and CTA action from the app code, so the content nor the CTA can be updated.
For such popup's in the future will keep this in mind.
