### ISSUE TITLE
Data jump from 3.1Cr to 4.9Cr in less than a day

### ISSUE THREAD

**Issue by ishannadkarni** [Share-Impact/iOS-Impact-Issues#29]
**Describe the bug**
Cause detail page showed 3.1Cr in 1.5L workouts in 17 days at 10.04pm.
And after a few seconds showed 4.92Cr in 1.67L workouts in 17 days.
How did so much get raised in a day?

**To Reproduce**
Open app:
1. Go to cause detail
2. Go back
3. Kill app
4. Open and hop to cause detail to see refreshed data.

**Expected behavior**
So much fundraise in a day isn't possible. It should be feasible growth rate by community. 

**Screenshots**

![image](https://user-images.githubusercontent.com/64792502/87251950-087c0600-c48d-11ea-8afd-60cc9c92bcbc.png)

![image](https://user-images.githubusercontent.com/64792502/87251951-0f0a7d80-c48d-11ea-98eb-9bb4caf26884.png)
 

Smartphone:**
 - Device:  iPhoneXR
 - OS: [e.g. iOS13

**Additional content**

15.3L workouts raised 3.1Cr in 17 days - average of Rs 20 donation per workout. Sounds about right.

Next refreshed screenshot - 16.9L workouts raised 4.92Cr in 17days!

So the latest 1.6L workouts raised 1.8Cr - remaining avg of recent/today's workouts - 100Rs per workout. How?

**Comment by ishannadkarni** [comment]
https://ced.impactrun.com/rundetail/42042328 - this user’s 1.48 Cr workout of 1862472101 steps was the root cause. 
How to eliminate such occurrence altogether in an automated scalable way?

**Comment by nik6018** [comment]
I think the backend team will have more insights to answer this question. You're welcome to reopen the issue if you think something can be done from the client side as well.
