### ISSUE TITLE
Steps and km not updating on homepage after exiting JLL league

### ISSUE THREAD

**Issue by aayush-khandelwal** [Share-Impact/iOS-Impact-Issues#3]
**Describe the bug**
After exiting the league, the steps and km were showing 0 on homepage but differently on streak page.

**To Reproduce**
1. Exit JLL league
2. Check homepage stats
3. Check stats on streak page

**Expected behavior**
Both screen should show same stats

**Screenshots**
Unable to find attachment option in android app of github

**Smartphone (please complete the following information):**
 - Device: [Oneplus 7]
 - OS: [Android 10]
 - Version [2.14.0]

**Additional context**
- Add any other context about the problem - here.

**Comment by nik6018** [comment]
@aayush-khandelwal  This is iOS issue tracker
