### ISSUE TITLE
Notification red badge automatically disappears 

### ISSUE THREAD

**Issue by sagrgpt** [Share-Impact/iOS-Impact-Issues#5]
**Describe the bug**
Notification icon red dot disappears after waiting for sometime on the homescreen. If you click on any other tab from the bottom navigation and cone back to homescreen, the red dot appears and then disappears after some time on the notification icon. 
**To Reproduce**
1. Open the app
2. Click on more tab
3. Click on home tab
4. Notification icon with +5 appears. 
5. +5 automatically disappears. 

**Expected behavior**
+5 should either not appear or should not disappear. The presence of the badge should depend on the number of unseen notifications. 

**Screenshots**
![01691121-3DD8-4B1F-B28A-D3D9723C9A16](https://user-images.githubusercontent.com/11998999/81308248-2e58e900-909f-11ea-8eaf-351e89aec5af.jpeg)
![9B09FE16-D3FB-4C79-B5F4-3C0EC90943D6](https://user-images.githubusercontent.com/11998999/81308266-36188d80-909f-11ea-9725-4b663070fa36.jpeg)

**Smartphone (please complete the following information):**
 - Device: [e.g. iPhone6] iphone6
 - OS: [e.g. iOS8.1] ios13.3
 - Version [e.g. 22] 3.5.25(1)

**Additional context**
NA

**Comment by gauravchauhan677** [comment]
We have identified and fixed this issue.
