### ISSUE TITLE
Post detail screen not loading

### ISSUE THREAD

**Issue by sagrgpt** [Share-Impact/iOS-Impact-Issues#9]
**Describe the bug**
Post detail screen wont load untill I click on clap. Also the bottom input container is raised. 

**To Reproduce**
1. Click on a post notification from notification center
2. Post details screen doesnot load properly. 

**Expected behavior**
Post detail screen should load properly or incase of network error should show a network error toast. 

**Screenshots**
![344555F8-E022-4B87-BC1C-1841D3355DD2](https://user-images.githubusercontent.com/11998999/81799217-a6eff780-952e-11ea-9db9-6ed3389e0b7f.png)

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**
 - Device: [e.g. iPhone6] 6s
 - OS: [e.g. iOS8] 13
 - Version [e.g. 22] 3.5.27(1)

**Additional context**

**Comment by gauravchauhan677** [comment]
We have identified and fixed this issue.
